### ISSUE TITLE
Summitpost HTTP 413

### ISSUE THREAD

**Issue by jaimemarijke** [thatneat/trfind#1]
Trying to submit the form to scrape summitpost results in a 413:

"HTTP Error 413: Request entity too large: request URL path too large"

**Comment by Spectre5** [comment]
Should be fixed by eacc52bb4818c559cdac0dfd53ca48a82fafeec4

**Comment by jason-curtis** [comment]
closed via #10 . fix is live! Thanks @Spectre5
