### ISSUE TITLE
 urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by jason-curtis** [thatneat/trfind#9]
probably one of the finders is broken. lemme take a look

**Comment by Spectre5** [comment]
Was this the cascadeclimbers issue fixed by 6bcf7f8912dcc622f6ff93b1fc7af1ee7eef2773?  If so, it can be closed, otherwise can you provide more details?

**Comment by jason-curtis** [comment]
yeah, looks good to me. super stale, sorry
